jobs:
  build-and-push-docker:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: meta
      name: get tags
      uses: docker/metadata-action@v4
      with:
        images: 'mockserver/mockserver

          '
        tags: 'type=match,pattern=(.*),group=1

          type=match,pattern=mockserver-(.*),group=1

          '
    - continue-on-error: true
      name: set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: set up docker buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: login to DockerHub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      if: inputs.tag != ''
      name: build and push (tag override)
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ inputs.tag }}
    - continue-on-error: true
      if: inputs.tag == ''
      name: build and push (tag from release)
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
name: Push Image To Docker Hub
on:
  repository_dispatch:
    types: trigger-ga___build-docker-image.yml
